# SPDX-License-Identifier: CC0-1.0
#
# Portions of this software were developed under sponsorship
# from the FreeBSD Foundation
build:
  stage: build
  image: gcc
  script:
    - make
  artifacts:
    paths:
      - utility/bsddialog

build-alpine:
    stage: build
    image: alpine:latest
    script:
      - apk update; apk add ncurses-dev gcc clang20 make
      - make
      - make clean
      - CC=clang make
    artifacts:
      paths:
        - utility/bsddialog

build-fedora:
    stage: build
    image: fedora:latest
    script:
      - dnf update --quiet --assumeyes; dnf install --quiet --assumeyes ncurses-devel gcc
      - make
    artifacts:
      paths:
        - utility/bsddialog
